print('Olá, Mundo!')
print()
print('Desafio 01')
nome = input('Qual o seu nome? ')
print('Olá, ',nome,'. É um prazer te conhecer!')
print()
print('Desafio 02')
dia = input('Qual o dia do seu nascimento? (Formato xx) ')
mes = input('Qual o mês do seu nascimento? (Formato xx) ')
ano = input('Qual o ano do seu nascimento? (Formato xxxx) ')
print('Sua data de nascimento é: ',dia,'/',mes,'/',ano,'.')
print()
print('Desafio 03')
num1 = int(input('Insira o primeiro número: '))
num2 = int(input('Insira o segundo número: '))
soma = num1 + num2
print('A soma dos números inseridos é igual a ', str(soma))